apiVersion: ptp.openshift.io/v1
kind: PtpConfig
metadata:
  name: ens3f1-oc-ptp-config
  namespace: openshift-ptp
spec:
  profile:
  - interface: ens3f1
    name: ens3f1-oc-ptp-config
    ptp4lConf: "[global]\n#\n# Default Data Set\n#\ntwoStepFlag 1\nslaveOnly 1\npriority1
      128\npriority2 128\ndomainNumber 24\n#utc_offset 37\nclockClass 248\nclockAccuracy
      0xFE\noffsetScaledLogVariance 0xFFFF\nfree_running 0\nfreq_est_interval 1\ndscp_event
      0\ndscp_general 0\ndataset_comparison ieee1588\nG.8275.defaultDS.localPriority
      128\n#\n# Port Data Set\n#\nlogAnnounceInterval -3\nlogSyncInterval -4\nlogMinDelayReqInterval
      -4\nlogMinPdelayReqInterval -4\nannounceReceiptTimeout 3\nsyncReceiptTimeout
      0\ndelayAsymmetry 0\nfault_reset_interval 4\nneighborPropDelayThresh 20000000\nmasterOnly
      0\nG.8275.portDS.localPriority 128\n#\n# Run time options\n#\nassume_two_step
      0\nlogging_level 7\npath_trace_enabled 0\nfollow_up_info 0\nhybrid_e2e 0\ninhibit_multicast_service
      0\nnet_sync_monitor 0\ntc_spanning_tree 0\ntx_timestamp_timeout 50 \nunicast_listen
      0\nunicast_master_table 0\nunicast_req_duration 3600\nuse_syslog 1\nverbose
      0\nsummary_interval -4\nkernel_leap 1\ncheck_fup_sync 0\n#\n# Servo Options\n#\npi_proportional_const
      0.0\npi_integral_const 0.0\npi_proportional_scale 0.0\npi_proportional_exponent
      -0.3\npi_proportional_norm_max 0.7\npi_integral_scale 0.0\npi_integral_exponent
      0.4\npi_integral_norm_max 0.3\nstep_threshold 0.0\nfirst_step_threshold 0.00002\nmax_frequency
      900000000\nclock_servo pi\nsanity_freq_limit  200000000\nntpshm_segment 0\n#\n#
      Transport options\n#\ntransportSpecific 0x0\nptp_dst_mac 01:1B:19:00:00:00\np2p_dst_mac
      01:80:C2:00:00:0E\nudp_ttl 1\nudp6_scope 0x0E\nuds_address /var/run/ptp4l\n#\n#
      Default interface options\n#\nclock_type OC\nnetwork_transport L2\ndelay_mechanism
      E2E\ntime_stamping hardware\ntsproc_mode filter\ndelay_filter moving_median\ndelay_filter_length
      10\negressLatency 0\ningressLatency 0\nboundary_clock_jbod 0\n#\n# Clock description\n#\nproductDescription
      ;;\nrevisionData ;;\nmanufacturerIdentity 00:00:00\nuserDescription ;\ntimeSource
      0xA0\n"
    ptp4lOpts: -s -2
    ptpSchedulingPolicy: SCHED_FIFO
    ptpSchedulingPriority: 10
  recommend:
  - match:
    - nodeLabel: node-role.kubernetes.io/worker
      nodeName: cnfde7.ptp.lab.eng.bos.redhat.com
    priority: 10
    profile: ens3f1-oc-ptp-config
